services:
  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: school
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

  estudiante:
    build:
      context: ./estudiante
      dockerfile: Dockerfile
    container_name: estudiante
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app-network

  evaluacion:
    build:
      context: ./evaluacion
      dockerfile: Dockerfile
    container_name: evaluacion
    ports:
      - "8081:8080"
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
